export const pathsMenu = {
   home: "/",
   experiencias: "/experiencias",
   expPersonalizar: "/experiencias/personalizar",
   expPersonalizada: "/experiencias/personalizada",
   sobre: "/lets-team",
   contato: "/lets-talk",
   blog: "/blog",
   carrinho: "/carrinho",
   minhaConta: "/cliente/minha-conta",
   dadosPessoais: "/cliente/dados-pessoais",
   meusMedidos: "/cliente/meus-pedidos",
   infoPagamento: "/cliente/informacoes-pagamento",
   login: "/cliente/login",
   intercambio: "/intercambio",
   voluntario: "/voluntario",
   guides: "/guias-de-viagem",
   esqueceuSenha: "/cliente/esqueceu-senha",
   checkout: "/checkout",
   obrigado: "/obrigado",
   search: "/experiencias/buscar",
   politica: "/politica-de-privacidade",
   wpp: "https://api.whatsapp.com/send?phone=551149332647&text=Ol%C3%A1%20Let%E2%80%99s%20Bora,%20%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es...",
   wpp2: "https://api.whatsapp.com/send?phone=551149332647&text=Ol%C3%A1%20Let%E2%80%99s%20Bora,%20%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es...",
   wppIntercambio: "https://api.whatsapp.com/send?phone=551149332647&text=Ol%C3%A1%20Let%E2%80%99s%20Bora,%20%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es..."
}